import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Mint from '@/components/Mint'
import {ethers} from 'ethers'

const inter = Inter({ subsets: ['latin'] })

declare global {
  interface Window { ethereum: any }
}

let provider: ethers.providers.Web3Provider;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Mint />
      </main>
    </>
  )
}
